# format 之前不能有任何的配置，否则 format 不生效
format = """
$time\
$directory\
$git_branch\
$git_status\
\n$character"""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#ffffff"
format = '[[ $time ](fg:#000000 bg:#ffffff)]($style)'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[character]
success_symbol = '[\$](bold green)'

# 禁用 package 组件，将其隐藏
[package]
disabled = true